skip_non_tags: true

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 11 x64
  - yarn
  - yarn run rebuild

build_script:
  - yarn run release

test: off

artifacts:
  - path: 'dist\*.exe'
  - path: 'dist\latest.yml'